name: hondi_ny
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  naver_map_plugin: ^0.9.6
  loading_animation_widget: ^1.2.0+1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  fonts:
    - family: jeju
      fonts:
        - asset: fonts/JejuGothic.ttf
        #저작권: 제주명조체, 제주특별자치도,
        #https://gongu.copyright.or.kr/gongu/wrt/wrt/view.do?wrtSn=419035&menuNo=200026
    - family: Suseong
      fonts:
        - asset: fonts/SuseongDotum.ttf
        #저작권: 수성돋음체, 대구광역시 수성구,
        # https://gongu.copyright.or.kr/gongu/wrt/wrt/view.do?wrtSn=13304311&menuNo=200023

  uses-material-design: true
